### PR TITLE
Fix ModuleFixerPlugin "provides" scanning

### PR DESCRIPTION
**Pull request by sormuras**
Stream all resources, don't filter ".class" ones.
Crop "META-INF/services/" from service name start.

### CODE REVIEW

**Comment by sormuras** [comment]
Re-fixes #14

**Comment by forax** [comment]
Hi Christian,
if you remove "private" in front of packageOf, i will accept your PR.

If packageOf is private, because packageOf is accessed inside an anonymous class, the compiler has to create an accessor method because the VM will not allow a class (even an anonymous class) to access to a private member [1].

[1] http://stackoverflow.com/questions/2199175/java-inner-outer-class-questions-about-outer-class-private-variables-access

**Comment by sormuras** [comment]
Done.

**Comment by forax** [comment]
Thanks Christian !

**Comment by sormuras** [comment]
De rien.

**Pull request merged**
